# Generated by Django 4.0.4 on 2022-05-10 04:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=32, unique=True)),
                ('stockName', models.CharField(default='', max_length=64)),
                ('industry', models.CharField(default='', max_length=64)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='', max_length=16, verbose_name='股價')),
                ('ud', models.CharField(default='', max_length=16, verbose_name='漲跌')),
                ('udpercent', models.CharField(default='', max_length=16, verbose_name='漲跌幅')),
                ('open', models.CharField(default='', max_length=16, verbose_name='開盤價')),
                ('yesterday', models.CharField(default='', max_length=16, verbose_name='昨收價')),
                ('high', models.CharField(default='', max_length=16, verbose_name='最高價')),
                ('low', models.CharField(default='', max_length=16, verbose_name='最低價')),
                ('volumn', models.CharField(default='', max_length=16, verbose_name='交易量')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockDetail', to='stock_name.stockname')),
            ],
        ),
    ]
