# Generated by Django 4.0.4 on 2022-04-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_name', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockName',
        ),
    ]
