# Generated by Django 4.0.4 on 2022-05-06 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockname',
            name='industry',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='stockname',
            name='list_date',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='stockname',
            name='market',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='stockname',
            name='securities',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='stockname',
            name='stock',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockname',
            name='stockName',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='stockname',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
