# Generated by Django 4.0.4 on 2022-05-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_name', '0002_stockname_industry_stockname_list_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockname',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
