# Generated by Django 4.0.4 on 2022-04-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_name', '0002_delete_stockname'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=10)),
                ('stockName', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
