# Generated by Django 4.0.4 on 2022-05-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_name', '0003_alter_stockname_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockname',
            name='id',
        ),
        migrations.AlterField(
            model_name='stockname',
            name='stock',
            field=models.CharField(default='', max_length=32, primary_key=True, serialize=False),
        ),
    ]
