# Generated by Django 4.0.4 on 2022-05-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_name', '0004_remove_stockname_id_alter_stockname_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockname',
            name='stock',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
