# Generated by Django 4.0.4 on 2022-05-06 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock_name', '0005_alter_stockname_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockname',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 5, 48, 28, 332271, tzinfo=utc)),
        ),
    ]
