# Generated by Django 4.0.4 on 2022-05-06 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_name', '0006_alter_stockname_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockname',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
