# Generated by Django 4.0.4 on 2022-05-09 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user_info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='電子信箱Email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='使用者名稱')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='註冊時間')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最後登入時間')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=10, validators=[user_info.models.gender_validate], verbose_name='性別')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user_info.models.MyAccountUser()),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit', models.CharField(max_length=64, verbose_name='水果')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
