# Generated by Django 4.0.4 on 2022-05-23 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user_info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_name', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='電子信箱Email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='使用者名稱')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手機')),
                ('gender', models.CharField(max_length=10, validators=[user_info.models.gender_validate], verbose_name='性別')),
                ('profile_image', models.ImageField(blank=True, default=user_info.models.get_default_profile_image, max_length=255, null=True, upload_to=user_info.models.get_profile_image_filepath, verbose_name='大頭照')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='註冊時間')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最後登入時間')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user_info.models.MyAccountUser()),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteStock', to='stock_name.stockname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteStock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='favoriteStocks',
            field=models.ManyToManyField(through='user_info.FavoriteStocks', to='stock_name.stockname'),
        ),
    ]
