# Generated by Django 4.0.4 on 2022-05-04 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最後登入時間'),
        ),
    ]
