# Generated by Django 4.0.4 on 2022-05-19 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_name', '0001_initial'),
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteStock', to='stock_name.stockname')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='favoriteStocks',
            field=models.ManyToManyField(through='user_info.FavoriteStocks', to='stock_name.stockname'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.AddField(
            model_name='favoritestocks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteStock', to=settings.AUTH_USER_MODEL),
        ),
    ]
