# Generated by Django 4.0.4 on 2022-05-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_favoritestocks_userinfo_favoritestocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritestocks',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
