# Generated by Django 4.0.4 on 2022-05-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_alter_userinfo_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://zentropy.s3.amazonaws.com/logo.png?AWSAccessKeyId=AKIAR6HU6UDDDIOR44X2&Signature=X%2F1a59SP8WWV5RugJ1jDr1LcsUk%3D&Expires=1653335237', max_length=255, null=True, upload_to='', verbose_name='大頭照'),
        ),
    ]
