# Generated by Django 4.0.4 on 2022-05-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_name', '0001_initial'),
        ('user_info', '0004_alter_userinfo_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='favoriteStocks',
            field=models.ManyToManyField(blank=True, through='user_info.FavoriteStocks', to='stock_name.stockname'),
        ),
    ]
